### ISSUE TITLE
Dubbo User Guide 中  <version>{you version}<version> 没有闭合

### ISSUE THREAD

**Issue by haochencheng** [yu199195/happylifeplat-tcc#14]
在你的接口项目中引入jar包，并在需要参与Tcc分布式事务的接口方法上添加@Tcc注解。
      <dependency>
          <groupId>com.happylifeplat.tcc</groupId>
          <artifactId>happylifeplat-tcc-annotation</artifactId>
          <version>{you version}<version>
      </dependency>
在你的实现项目中引入jar包，并在实现接口上添加: @Tcc(confirmMethod = "confirm", cancelMethod = "cancel")confirmMethod，cancelMethod对应为的方法名称
        <dependency>
            <groupId>com.happylifeplat.tcc</groupId>
            <artifactId>happylifeplat-tcc-dubbo</artifactId>
            <version>{you version}<version>
        </dependency>

**Comment by yu199195** [comment]
啥意思

**Comment by haochencheng** [comment]
JdbcCoordinatorRepository 这个类

 String sql = "insert into " + tableName + "(trans_id,target_class,target_method,retried_count,create_time,last_time,version,status,invocation,role,pattern)" +
                " values(?,?,?,?,?,?,?,?,?,?,?)";
